debug: true
scores:
  steve: 123
  alex: 432
teams:
  red:
    name: ยง4Red Reindeers
    chatColor: red
    players:
    - ArsonElu
  purple:
    name: ยง5Purple Pandas
    chatColor: dark_purple
    players:
    - TayaMc